name: Happy Coding
markdown: kramdown
future: true
kramdown:
  syntax_highlighter: rouge
permalink: /:categories/:slug
description: >
  Happy Coding is a collection of coding tutorials, examples, and blog posts,
  as well as a community of folks coding and learning together!
plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed